### ISSUE TITLE
GetMatchList issue

### ISSUE THREAD

**Issue by Taifunov** [MingweiSamuel/Camille#53]
I'm doing like in docs `var matchlist = await api.MatchV4.GetMatchlistAsync(region, summonerId, queue: new[] { 420 }, endIndex: 10);`

But get an error: `MingweiSamuel.Camille.Util.RiotResponseException: 'Request to match-v4.getMatchlist failed after 0 retries. (status: 400).'`

What i'm doing wrong?

**Comment by MingweiSamuel** [comment]
`getMatchlist` needs an `accountId` instead of summonerId - very easy mistake to make. - https://developer.riotgames.com/apis#match-v4/GET_getMatchlist

Let me know if that works.

Also note that match-v4 is deprecated will be replaced by match-v5 pretty soon, and it takes a PUUID :S https://developer.riotgames.com/apis#match-v5/GET_getMatchIdsByPUUID

**Comment by Taifunov** [comment]
Oh, thanks this is the reason :/
