### ISSUE TITLE
Rate limiting question

### ISSUE THREAD

**Issue by bugproof** [MingweiSamuel/Camille#61]
I don't really understand how these configuration keys work:

https://github.com/MingweiSamuel/Camille/blob/ecb5be76d6f4c1bee7cbc7bcc4020ba2e1e1cfe6/Camille.RiotGames/gen/configspec.json#L6-L20

What if I have 2 threads using the same `IRiotGamesApi` running independently of each other. How can I ensure that the limit will be equally assigned?

What if I have 2 processes using the same api key?

E.g. when I'm using development key rate limits are:

- 20 requests every 1 second
- 100 requests every 2 minutes

Can I somehow configure it so it will be 10req/1sec in process 1 and process 2? I mostly just used https://github.com/David-Desmaisons/RateLimiter in the past and that had a friendler configuration, but if this library can achieve the same then it'd be great too 

also 

> Note that rate limits are enforced per region. For example, with the above rate limit, you could make 20 requests every 1 second to both the NA and EUW League of Legends endpoints simultaneously.

Does the library handle that as well?

Thanks for the great library 🍺

**Comment by MingweiSamuel** [comment]
> What if I have 2 threads using the same IRiotGamesApi running independently of each other. How can I ensure that the limit will be equally assigned?

So with multiple _threads_, you can create one `RiotGamesApi` instance and share it between the threads and it will _just work_. Importantly the rate limit is _shared_ so that either thread can use up more of the rate limit if it needs to. So is thread A is making 19 req/sec and thread B is making 1 req/sec that will just work (thread A will get 95% of the rate limit).

But if you actually want to force the rate limit to _always be evenly divided between threads_ (which you should double check is what you actually want) you can make multiple `RiotGamesApi` instances and set the [`concurrentInstanceFactor`](http://www.mingweisamuel.com/Camille/v/3.x.x/docs/api/Camille.RiotGames.RiotGamesApiConfig.Builder.html#Camille_RiotGames_RiotGamesApiConfig_Builder_ConcurrentInstanceFactor) just as you would for multiple processes...

> What if I have 2 processes using the same api key?

With multiple _processes_, possibly even on different machines, then you will need to create a `RiotGamesApi` instance for each process. The rate limit in this case can't be shared (since there's no coordination between processes) so then you should use [`concurrentInstanceFactor`](http://www.mingweisamuel.com/Camille/v/3.x.x/docs/api/Camille.RiotGames.RiotGamesApiConfig.Builder.html#Camille_RiotGames_RiotGamesApiConfig_Builder_ConcurrentInstanceFactor) to divide up the rate limit...

> Can I somehow configure it so it will be 10req/1sec in process 1 and process 2?

If you had two processes and wanted to divide up the rate limit evenly, you could set `concurrentInstanceFactor=0.5` on both. That would be 10req/1sec, 50req/2min for each process.

If you expect one process to need more requests than the other, you could set `concurrentInstanceFactor=0.75` and `concurrentInstanceFactor=0.25` on the other, for example. Then the first would get 75% and second would get remaining 25% of the rate limit.

>> Note that rate limits are enforced per region.
>
> Does the library handle that as well?

The library handles regions 👌 , tracks rate limits separately for each region.

Cheers!
