### ISSUE TITLE
the swagger can't make some request

### ISSUE THREAD

**Issue by x0rld** [MingweiSamuel/Camille#92]
I tried to do some request directly from the swagger but it doesn't work 
![image](https://user-images.githubusercontent.com/45242856/180613487-f986163f-1ea7-4603-98eb-76f024d218ab.png)

**Comment by mikaeldui** [comment]
Is it the LCU, Game or RG-API Swagger?

If it's the LCU then you could try the specs at https://magisteriis.github.io/riot-games-help-to-swagger-dotnet/ which have more metadata added, but aren't 100% correct. Maybe those specs can help you narrow down the root cause of the issue.

I'd also suggest importing the specs into [Postman](https://www.postman.com/) to avoid any CORS issues caused by the browser.

**Comment by MingweiSamuel** [comment]
The riot api swagger codebase is here: https://github.com/MingweiSamuel/riotapi-schema

however it was never meant to work from browser due to CORS, and since the dev portal already has interactive requests

The lcu api swagger repo is here: https://github.com/MingweiSamuel/lcu-schema

If you want interactivity use lcu explorer: https://github.com/HextechDocs/lcu-explorer
